#!/usr/bin/env python3

import sys

def is_float(value):
    result = True 
    try:
       float(value)
    except Exception:
       result = False
    return result

if __name__ == '__main__':
    result = 0
    for i,line in enumerate(sys.stdin, start=1):
        line = line.strip()
        if not line:
            continue
        fields = line.split()
        for j,field in enumerate(fields, start=1):
             if not is_float(field):
                 print(f'at line {i} field {j} the value {line} is not a float')
                 sys.exit(1)
             result += float(field)
    print(result)
